version: "3.9"

services:
  web:
    image: allegro/ralph:latest
    restart: always
    ports:
      - "5527:8000"
    volumes:
      - ralph_media:/var/local/ralph/media
      - ralph_static:/usr/share/ralph/static
    environment:
      DATABASE_NAME: ralph_ng
      DATABASE_USER: ralph_ng
      DATABASE_PASSWORD: ralph_ng
      DATABASE_HOST: db
      REDIS_HOST: redis
      REDIS_PASSWORD: ""
      REDIS_PORT: 6379
      REDIS_DB: 0
      RALPH_INSTANCE: ${RALPH_INSTANCE}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
      USE_X_FORWARDED_HOST: "True"
      SECURE_PROXY_SSL_HEADER: "HTTP_X_FORWARDED_PROTO,https"
      DEBUG: ${DEBUG}

  nginx:
    image: allegro/ralph-static-nginx:latest
    restart: always
    ports:
      - "5528:80"
    volumes:
      - ralph_media:/opt/media
      - ralph_static:/usr/share/nginx/html/static:ro
    depends_on:
      - web

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ralph_ng
      MYSQL_ROOT_PASSWORD: ralph_ng
      MYSQL_USER: ralph_ng
      MYSQL_PASSWORD: ralph_ng
    volumes:
      - ralph_dbdata:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-flush-log-at-trx-commit=0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  inkpy:
    build:
      context: ../
      dockerfile: docker/Dockerfile-inkpy
    restart: always
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0

volumes:
  ralph_dbdata:
  ralph_media:
  ralph_static:
